#!/bin/bash

usage() {
    echo "touchp: \`mkdir -p\` equivalent for \`touch\`"
    echo "Usage: touchp FILE..."
    exit 1
}
while getopts ':h' c
do
    usage
done

check() {
    if [ "$?" -ne "0" ]; then
        echo Failed to execute command: $@
        exit 1
    fi
}

dirnames=""
for arg in $@; do
    dirnames+="`dirname ${arg}` "
done

mkdir -p $dirnames
check mkdir -p $dirnames

touch $@
check touch $@

